"""Aggregate results CSVs into mean+/-std and emit booktabs LaTeX tables.

Reads results/main_results.csv (and optionally results/ablations.csv) and writes:
  * results/main_results_agg.csv          (per cell: mean/std over seeds)
  * results/tables/main_table.tex         (MSE/MAE per dataset x horizon, all models;
                                            best in bold, second underlined)
  * results/tables/efficiency_table.tex   (params/FLOPs/sec-per-epoch/peak-mem)
  * results/tables/ablation_table.tex     (if ablations.csv present)

All numbers come straight from the CSVs the runners produced — nothing is
hand-entered. Run after run_experiments.py / run_ablations.py.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

DATASET_LABEL = {
    "ETTh1": "ETTh1", "ETTh2": "ETTh2", "ETTm1": "ETTm1", "ETTm2": "ETTm2",
    "weather": "Weather", "electricity": "Electricity",
}
MODEL_LABEL = {
    "naive": "Naive", "nlinear": "NLinear", "dlinear": "DLinear",
    "rlinear": "RLinear", "fits": "FITS", "patchtst": "PatchTST*",
    "freqlite": "FreqLite",
}
MODEL_ORDER = ["naive", "nlinear", "dlinear", "rlinear", "fits", "patchtst", "freqlite"]
DATASET_ORDER = ["ETTh1", "ETTh2", "ETTm1", "ETTm2", "weather", "electricity"]
HORIZON_ORDER = [96, 192, 336, 720]


def aggregate(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby(["model", "dataset", "lookback", "horizon"])
    agg = g.agg(
        mse_mean=("test_mse", "mean"), mse_std=("test_mse", "std"),
        mae_mean=("test_mae", "mean"), mae_std=("test_mae", "std"),
        params=("params", "first"),
        flops=("flops_per_series", "first"),
        sec_per_epoch=("sec_per_epoch", "mean"),
        peak_mem=("peak_gpu_mem_mb", "mean"),
        n_seeds=("seed", "nunique"),
    ).reset_index()
    agg["mse_std"] = agg["mse_std"].fillna(0.0)
    agg["mae_std"] = agg["mae_std"].fillna(0.0)
    return agg


def _fmt(mean: float, std: float) -> str:
    return f"{mean:.3f}\\textpm{std:.3f}"


def main_table_tex(agg: pd.DataFrame, L: int) -> str:
    sub = agg[agg["lookback"] == L]
    models = [m for m in MODEL_ORDER if m in sub["model"].unique()]
    datasets = [d for d in DATASET_ORDER if d in sub["dataset"].unique()]
    horizons = [h for h in HORIZON_ORDER if h in sub["horizon"].unique()]

    lines = []
    lines.append("% Auto-generated by scripts/make_tables.py — do not edit by hand.")
    lines.append("\\begin{table*}[t]")
    lines.append("\\centering")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append(f"\\caption{{Long-term forecasting results (lookback $L={L}$). "
                 "Each cell is test MSE/MAE (mean$\\pm$std over 3 seeds) in the "
                 "train-standardized space. \\textbf{Bold}: best; \\underline{underline}: "
                 "second best. PatchTST* uses a 4\\,GB-feasible small config.}")
    lines.append(f"\\label{{tab:main_L{L}}}")
    ncols = 2 + 2 * len(models)
    lines.append("\\begin{tabular}{ll" + "c" * (2 * len(models)) + "}")
    lines.append("\\toprule")
    head = "Dataset & $H$ "
    for m in models:
        head += f"& \\multicolumn{{2}}{{c}}{{{MODEL_LABEL[m]}}} "
    lines.append(head + "\\\\")
    # metric subheader
    sub_idx = []
    for i, _ in enumerate(models):
        c0 = 3 + 2 * i
        sub_idx.append(f"\\cmidrule(lr){{{c0}-{c0+1}}}")
    lines.append(" ".join(sub_idx))
    sub2 = "& "
    for _ in models:
        sub2 += "& MSE & MAE "
    lines.append(sub2 + "\\\\")
    lines.append("\\midrule")

    for d in datasets:
        for hi, h in enumerate(horizons):
            cell = sub[(sub["dataset"] == d) & (sub["horizon"] == h)]
            if cell.empty:
                continue
            # find best/second per metric for bolding (lower is better)
            mse_vals = {m: cell[cell.model == m]["mse_mean"].values for m in models}
            mae_vals = {m: cell[cell.model == m]["mae_mean"].values for m in models}
            mse_vals = {m: v[0] for m, v in mse_vals.items() if len(v)}
            mae_vals = {m: v[0] for m, v in mae_vals.items() if len(v)}
            # exclude naive from ranking (sanity floor, not a competitor)
            rankable = [m for m in mse_vals if m != "naive"]
            mse_sorted = sorted(rankable, key=lambda m: mse_vals[m])
            mae_sorted = sorted(rankable, key=lambda m: mae_vals[m])
            best_mse = mse_sorted[0] if mse_sorted else None
            sec_mse = mse_sorted[1] if len(mse_sorted) > 1 else None
            best_mae = mae_sorted[0] if mae_sorted else None
            sec_mae = mae_sorted[1] if len(mae_sorted) > 1 else None

            dlabel = DATASET_LABEL[d] if hi == 0 else ""
            row = f"{dlabel} & {h} "
            for m in models:
                c = cell[cell.model == m]
                if c.empty:
                    row += "& -- & -- "
                    continue
                msem, mses = c["mse_mean"].values[0], c["mse_std"].values[0]
                maem, maes = c["mae_mean"].values[0], c["mae_std"].values[0]
                ms = _fmt(msem, mses)
                ma = _fmt(maem, maes)
                if m == best_mse:
                    ms = f"\\textbf{{{ms}}}"
                elif m == sec_mse:
                    ms = f"\\underline{{{ms}}}"
                if m == best_mae:
                    ma = f"\\textbf{{{ma}}}"
                elif m == sec_mae:
                    ma = f"\\underline{{{ma}}}"
                row += f"& {ms} & {ma} "
            lines.append(row + "\\\\")
        lines.append("\\midrule")
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table*}")
    return "\n".join(lines) + "\n"


def efficiency_table_tex(agg: pd.DataFrame, L: int, dataset: str = "ETTh1") -> str:
    sub = agg[(agg["lookback"] == L) & (agg["dataset"] == dataset)]
    models = [m for m in MODEL_ORDER if m in sub["model"].unique()]
    horizons = [h for h in HORIZON_ORDER if h in sub["horizon"].unique()]
    lines = []
    lines.append("% Auto-generated by scripts/make_tables.py.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append(f"\\caption{{Efficiency on {DATASET_LABEL.get(dataset, dataset)} "
                 f"($L={L}$, RTX 3050\\,Ti 4\\,GB): parameter count, analytic "
                 "FLOPs/series, train time per epoch (s), and peak GPU memory (MB). "
                 "Params/FLOPs shown for $H{=}96$ and $H{=}720$.}")
    lines.append(f"\\label{{tab:efficiency_L{L}}}")
    lines.append("\\begin{tabular}{lrrrrr}")
    lines.append("\\toprule")
    lines.append("Model & Params (96) & Params (720) & FLOPs/s (720) & s/epoch & "
                 "Peak Mem (MB) \\\\")
    lines.append("\\midrule")
    for m in models:
        c96 = sub[(sub.model == m) & (sub.horizon == 96)]
        c720 = sub[(sub.model == m) & (sub.horizon == 720)]
        p96 = int(c96["params"].values[0]) if not c96.empty else 0
        p720 = int(c720["params"].values[0]) if not c720.empty else 0
        fl = int(c720["flops"].values[0]) if not c720.empty else 0
        spe = sub[sub.model == m]["sec_per_epoch"].mean()
        mem = sub[sub.model == m]["peak_mem"].max()
        flstr = f"{fl:,}" if fl > 0 else "--"
        lines.append(f"{MODEL_LABEL[m]} & {p96:,} & {p720:,} & {flstr} & "
                     f"{spe:.2f} & {mem:.0f} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def ablation_table_tex(path: Path) -> str:
    df = pd.read_csv(path)
    g = df.groupby(["variant", "dataset", "horizon"]).agg(
        mse_mean=("test_mse", "mean"), mse_std=("test_mse", "std"),
        mae_mean=("test_mae", "mean"),
        params=("params", "first"),
    ).reset_index()
    g["mse_std"] = g["mse_std"].fillna(0.0)
    # average MSE/MAE across the ablation subset per variant (compact summary)
    summ = df.groupby("variant").agg(
        mse=("test_mse", "mean"), mae=("test_mae", "mean"),
        params=("params", "mean"),
    ).reset_index()
    order = ["A0_full", "A1_revin", "A2_fixedMA", "A3_K1_arevin", "A4_K1_revin",
             "A5_K3", "A5_K4", "A6_gate", "A7_frozen", "A8_no_lambda"]
    label = {
        "A0_full": "A0: Full FreqLite",
        "A1_revin": "A1: $-$A-RevIN (plain RevIN)",
        "A2_fixedMA": "A2: fixed MA split",
        "A3_K1_arevin": "A3: $K{=}1$ + A-RevIN",
        "A4_K1_revin": "A4: $K{=}1$ + RevIN ($\\equiv$RLinear)",
        "A5_K3": "A5: $K{=}3$ bands",
        "A5_K4": "A5: $K{=}4$ bands",
        "A6_gate": "A6: gated recombination",
        "A7_frozen": "A7: frozen decomposition",
        "A8_no_lambda": "A8: $-\\lambda$ drift term",
    }
    lines = ["% Auto-generated by scripts/make_tables.py.",
             "\\begin{table}[t]", "\\centering",
             "\\caption{Ablation study (mean test MSE/MAE over the subset "
             "\\{ETTh1, ETTm2, Weather\\}$\\times H\\in\\{96,720\\}\\times$3 seeds, "
             "$L=336$). Each variant degenerates a single FreqLite component.}",
             "\\label{tab:ablation}",
             "\\begin{tabular}{lrrr}", "\\toprule",
             "Variant & Avg MSE & Avg MAE & Avg Params \\\\", "\\midrule"]
    present = [v for v in order if v in set(summ["variant"])]
    best = summ[summ.variant.isin([v for v in present if v != "A4_K1_revin"])]["mse"].min()
    for v in present:
        r = summ[summ.variant == v].iloc[0]
        mse = f"{r['mse']:.3f}"
        if abs(r["mse"] - best) < 1e-9:
            mse = f"\\textbf{{{mse}}}"
        lines.append(f"{label[v]} & {mse} & {r['mae']:.3f} & "
                     f"{int(round(r['params'])):,} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--main", default="results/main_results.csv")
    ap.add_argument("--ablations", default="results/ablations.csv")
    ap.add_argument("--lookbacks", default="336,96")
    args = ap.parse_args()

    tables_dir = ROOT / "results" / "tables"
    tables_dir.mkdir(parents=True, exist_ok=True)

    main_path = ROOT / args.main
    if main_path.exists():
        df = pd.read_csv(main_path)
        agg = aggregate(df)
        agg.to_csv(ROOT / "results" / "main_results_agg.csv", index=False)
        print(f"wrote results/main_results_agg.csv ({len(agg)} cells)")
        for L in [int(x) for x in args.lookbacks.split(",")]:
            if (agg["lookback"] == L).any():
                (tables_dir / f"main_table_L{L}.tex").write_text(
                    main_table_tex(agg, L), encoding="utf-8")
                (tables_dir / f"efficiency_table_L{L}.tex").write_text(
                    efficiency_table_tex(agg, L), encoding="utf-8")
                print(f"wrote main_table_L{L}.tex, efficiency_table_L{L}.tex")
    else:
        print(f"no {main_path} yet — skipping main/efficiency tables")

    abl_path = ROOT / args.ablations
    if abl_path.exists():
        (tables_dir / "ablation_table.tex").write_text(
            ablation_table_tex(abl_path), encoding="utf-8")
        print("wrote ablation_table.tex")
    else:
        print(f"no {abl_path} yet — skipping ablation table")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
